### ISSUE TITLE
Implementar Google Analytics

### ISSUE THREAD

**Issue by guuibayer** [guuibayer/barragens#4]
https://github.com/react-ga/react-ga

**Comment by francisrod01** [comment]
Implementação customizada.
https://github.com/react-ga/react-ga/issues/332

**Comment by guuibayer** [comment]
Sim, da pra chamarmos o inicializador dele no App.js e depois chamarmos o método de hit dentro dos componentes

Seria interessante mandar alguma outra informação além do nome das páginas?

```
ReactGA.pageview('/about')
ReactGA.pageview('/map')
```

**Comment by francisrod01** [comment]
Eu não sei porque, mas se você tentar mandar o título, no debug do Analytics vai mostrar o título da rota que você acessou anteriormente.

**Comment by GiovanniSM20** [comment]
Por qual motivo será usado o Google Analytics ?

**Comment by guuibayer** [comment]
@GiovanniSM20 como comentei no Gitter, o motivo seria mais a título de curiosidade de quais seriam as barragens mais visualizadas, já que coloquei a chamada do GA para elas além das páginas.
